spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_app
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n/messages

  jpa:
    hibernate:
      ddl-auto: validate

resilience4j:
  circuitbreaker:
    instances:
      getAllStudents:
        # configs for close state
        sliding-window-type: count_based
        failure-rate-threshold: 50.0
        sliding-window-size: 6
        # configs for open state
        wait-duration-in-open-state: 10s
        # configs for hal-open state
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2
        max-wait-duration-in-half-open-state: 15000